version: '3.9'
services:
  sqldb:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_DATABASE=sdntool
      - MYSQL_ROOT_PASSWORD=tmpsqlpass
      - MYSQL_ROOT_HOST=10.2.0.6
    volumes:
      - sqldb_data:/var/lib/mysql
    networks:
      sdntool_private_network:
        ipv4_address: 10.2.0.2

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      sdntool_private_network:
        ipv4_address: 10.2.0.3

  neo4j:
    image: 'neo4j:latest'
    expose:
      - '7474'
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=true
      - NEO4J_AUTH=neo4j/cdcjucdcju
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

    networks:
      sdntool_private_network:
        ipv4_address: 10.2.0.4

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/mongodb
    networks:
      sdntool_private_network:
        ipv4_address: 10.2.0.5
        
  web:
    build: .
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        celery -A sdnproject worker --detach -f celery.log
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=1
      - SOFTWARE_NAME=SDNToolv1.0
      - SYSTEM_TIMEZONE=Asia/Kolkata
      - SECRET_KEY=qo1+kq2)$b(kfgrl7s2eht+=7myltu#&+#w3-gdyu79y-)-=5d
      - ALLOWED_HOSTS=*
      - MYSQL_DB_HOST=10.2.0.2
      - MYSQL_DB_NAME=sdntool
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=tmpsqlpass
      - MYSQL_DB_PORT=3306
      - MONGODB_URI=mongodb://10.2.0.5:27017
      - MONGODB_DB_NAME=cdcju
      - NEO4J_URI=bolt://10.2.0.4:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=cdcjucdcju
      - CELERY_BROKER_URL=redis://10.2.0.3:6379
      - CELERY_RESULT_BACKEND=redis://10.2.0.3:6379

    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      sdntool_private_network:
        ipv4_address: 10.2.0.6
      accessible_network:
networks:
  sdntool_private_network:
    driver: macvlan
    ipam:
      config:
        - subnet: 10.2.0.0/16
          gateway: 10.2.0.1
  accessible_network:
    driver: bridge
volumes:
    sqldb_data:
    mongodb_data:
    neo4j_data:
    neo4j_import:
    neo4j_plugins:
